---
# tasks file for libvirtd


- name: install packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{libvirtd_packages}}"
  tags:
    - packages

- name: ensure libvirtd is started if not started
  service: 
    name: libvirtd
    state: started


- name: add libvirtd users
  user:
    name: "{{item}}"
    groups: libvirt
    append: yes
  with_items: "{{libvirtd_users}}"
