---
# tasks file for libvirtd


- name: install packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{libvirtd_packages}}"
  tags:
    - packages

- name: ensure libvirtd is started if not started
  service: 
    name: libvirtd
    state: started


- name: add libvirtd users
  user:
    name: "{{item}}"
    groups: libvirt
    append: yes
  with_items: "{{libvirtd_users}}"


#copy download_isos.sh to /usr/local/bin
- name: copy download_isos.sh to /usr/local/bin
  ansible.builtin.copy:
    src: download_isos.sh
    dest: /usr/local/bin/download_isos.sh
    mode: '0755'
    owner: root
    group: root
  tags:
    - download_isos
